# -*- coding: utf-8 -*-
"""Milestone 3 graph codes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aJfxbQsbUNTY99BCUV_JddEIysTWehmT
"""

#Graph-1
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import lognorm, norm

mu = 0.0
sigma = 0.8

R = np.linspace(0.001, 10, 500)

pdf_R = lognorm.pdf(R, s=sigma, scale=np.exp(mu))

X = 10 * np.log10(R)

mu_X = np.mean(X)
sigma_X = np.std(X)

x_vals = np.linspace(-30, 25, 500)
pdf_X = norm.pdf(x_vals, mu_X, sigma_X)

fig, ax = plt.subplots(1, 2, figsize=(12,5))

ax[0].plot(R, pdf_R, color="blue", linewidth=2)
ax[0].fill_between(R, pdf_R, alpha=0.3, color="blue")
ax[0].axvline(0.1, linestyle="--", color="red", label="0.1 mm/h threshold")

ax[0].set_title("Raw State Variable\nR(x,t) ~ LogNormal(μ,σ²)")
ax[0].set_xlabel("Rainfall Intensity R (mm/h)")
ax[0].set_ylabel("Probability Density")
ax[0].legend()

ax[1].plot(x_vals, pdf_X, color="orange", linewidth=2)
ax[1].fill_between(x_vals, pdf_X, alpha=0.3, color="orange")
ax[1].axvline(-15, linestyle="--", color="red", label="-15 dBR dry pixel floor")

ax[1].set_title("Transformed Latent State\nX = 10 log10(R)")
ax[1].set_xlabel("Log-Transformed Intensity X (dBR)")
ax[1].set_ylabel("Probability Density")
ax[1].legend()

plt.tight_layout()
plt.show()

#Graph-2
import numpy as np
import matplotlib.pyplot as plt

lambdas = [10, 20, 40]  # decorrelation lengths (km)
h = np.linspace(0, 100, 400)

fig, ax = plt.subplots(1, 2, figsize=(12,5))

for lam in lambdas:
    rho = np.exp(-h/lam)
    ax[0].plot(h, rho, linewidth=2, label=f"λ = {lam} km")

ax[0].axhline(np.exp(-1), linestyle="--", color="gray", label="1/e ≈ 0.37")

ax[0].set_title("Exponential Spatial Correlation\nρ(h) = e^{-h/λ}")
ax[0].set_xlabel("Distance h (km)")
ax[0].set_ylabel("Correlation ρ(h)")
ax[0].set_xlim(0,100)
ax[0].set_ylim(0,1.05)
ax[0].legend()

lam = 20

x = np.linspace(-60, 60, 200)
y = np.linspace(-60, 60, 200)
X, Y = np.meshgrid(x, y)

h2d = np.sqrt(X**2 + Y**2)
rho2d = np.exp(-h2d/lam)

cont = ax[1].contourf(X, Y, rho2d, levels=20, cmap="Blues")

circle = plt.Circle((0,0), lam, color="white", fill=False, linestyle="--", linewidth=2)
ax[1].add_patch(circle)

ax[1].set_title("2D Spatial Correlation Field\n(λ = 20 km)")
ax[1].set_xlabel("Δx (km)")
ax[1].set_ylabel("Δy (km)")
ax[1].set_aspect("equal")

fig.colorbar(cont, ax=ax[1], label="ρ(h)")

plt.tight_layout()
plt.show()

#Graph-3
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0,100,200)
y = np.linspace(0,100,200)
X,Y = np.meshgrid(x,y)

def gaussian(x0,y0,amp,sigma):
    return amp*np.exp(-((X-x0)**2+(Y-y0)**2)/(2*sigma**2))

R = gaussian(30,35,6,12) + gaussian(70,75,5,10)

u = 0.6
v = 0.4

U = np.ones_like(X)*u
V = np.ones_like(Y)*v
dt = 10
shift_x = int(u*dt)
shift_y = int(v*dt)

R_forecast = np.roll(R, shift_x, axis=1)
R_forecast = np.roll(R_forecast, shift_y, axis=0)
fig, ax = plt.subplots(1,2,figsize=(12,5))

c1 = ax[0].contourf(X,Y,R,25,cmap="YlOrRd")

step = 25
mask = R[::step,::step] > 0.5

ax[0].quiver(
    X[::step,::step][mask],
    Y[::step,::step][mask],
    U[::step,::step][mask],
    V[::step,::step][mask],
    color="navy",
    scale=10
)

ax[0].set_title("Observed $R(x,t)$ + Velocity $V(x,t)$")
ax[0].set_xlabel("x (km)")
ax[0].set_ylabel("y (km)")

plt.colorbar(c1,ax=ax[0],label="Rain rate (mm/h)")

c2 = ax[1].contourf(X,Y,R_forecast,25,cmap="YlOrRd")

ax[1].set_title("Forecast $\hat{R}(x,t+Δt)$")
ax[1].set_xlabel("x (km)")
ax[1].set_ylabel("y (km)")

plt.colorbar(c2,ax=ax[1],label="Rain rate (mm/h)")

plt.tight_layout()
plt.show()

#Graph-4
import numpy as np
import matplotlib.pyplot as plt

lead = np.array([0,30,60,90,120,150,180,240,300,360])

rmse = np.array([0.3,1.8,2.7,3.2,3.7,4.1,4.5,5.0,5.4,5.7])
mae  = np.array([0.1,1.2,1.7,2.1,2.4,2.7,3.0,3.3,3.6,3.8])

csi  = np.array([0.90,0.72,0.60,0.52,0.45,0.39,0.34,0.27,0.20,0.15])

fig,ax = plt.subplots(1,2,figsize=(12,5))

ax[0].plot(lead,rmse,'o-',color='blue',label='RMSE')
ax[0].plot(lead,mae,'o--',color='orange',label='MAE')

ax[0].axvspan(0,60,color='green',alpha=0.15)
ax[0].axvspan(60,180,color='yellow',alpha=0.15)
ax[0].axvspan(180,360,color='red',alpha=0.15)

ax[0].text(10,5.3,'High\naccuracy',color='green')
ax[0].text(80,5.3,'Moderate\nskill',color='orange')
ax[0].text(210,5.3,'Rapid\ndegradation',color='red')

ax[0].set_xlabel("Lead Time τ (minutes)")
ax[0].set_ylabel("Error (mm/h)")
ax[0].set_title("Forecast Error Growth with Lead Time\n(Deterministic Lagrangian Persistence)")
ax[0].legend()
ax[0].grid(alpha=0.3)

ax[1].plot(lead,csi,'o-',color='blue',label='CSI (0.1 mm/h threshold)')

ax[1].axhline(0.5,color='red',linestyle='--',label='Useful skill threshold (CSI=0.5)')

ax[1].axvline(80,color='green',linestyle=':',label='Predictability limit')

ax[1].text(82,0.55,"τ ≈ 80 min\n(predictability limit)",color='green')

ax[1].axvspan(80,360,color='red',alpha=0.15,label='Skill breakdown region')

ax[1].set_xlabel("Lead Time τ (minutes)")
ax[1].set_ylabel("Critical Success Index (CSI)")
ax[1].set_title("CSI vs. Lead Time\n(Deterministic Baseline)")
ax[1].set_ylim(0,1)
ax[1].legend()
ax[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

#Graph-5
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

x = np.linspace(-5,5,400)

stds = [0.7, 1.0, 1.5, 2.0]
labels = ["τ = 30 min","τ = 60 min","τ = 120 min","τ = 180 min"]
colors = ["#1f77b4","#ff7f0e","#2ca02c","#d62728"]

fig,ax = plt.subplots(1,2,figsize=(12,5))

for s,l,c in zip(stds,labels,colors):
    pdf = norm.pdf(x,0,s)
    ax[0].plot(x,pdf,label=l,color=c,linewidth=2)

ax[0].axvline(0,color="gray",linestyle="--")

ax[0].set_title("PDF of Forecast Error\nat Different Lead Times")
ax[0].set_xlabel("Forecast Error (mm/h)")
ax[0].set_ylabel("Probability Density")
ax[0].legend()

ax[0].text(1.5,0.4,"Distributions widen\nas uncertainty grows",
           bbox=dict(facecolor="white",alpha=0.8))

ax[0].grid(alpha=0.3)

for s,l,c in zip(stds,labels,colors):
    cdf = norm.cdf(x,0,s)
    ax[1].plot(x,cdf,label=l,color=c,linewidth=2)

ax[1].axvline(0,color="gray",linestyle="--")

ax[1].set_title("CDF of Forecast Error\n(Shallower slope = higher uncertainty)")
ax[1].set_xlabel("Forecast Error (mm/h)")
ax[1].set_ylabel("Cumulative Probability F(x)")
ax[1].legend()

ax[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import lognorm

plt.style.use("seaborn-v0_8-whitegrid")

fig, ax = plt.subplots(1,2,figsize=(13,5))

t = np.linspace(0,1,200)
x_true = 20 + 80*t
y_true = 30 + 35*np.log1p(2*t)

ax[0].plot(x_true,y_true,color="#1f77b4",linewidth=2,label="True storm trajectory")

x_pred = np.linspace(20,80,200)
y_pred = np.linspace(30,78,200)

ax[0].plot(x_pred,y_pred,'--',color="#d62728",linewidth=2,label="Frozen V prediction")
ax[0].scatter(20,30,color="black",s=80,label="t = 0",zorder=3)


points = [(30,38,"t = 1h"),
          (50,53,"t = 3h"),
          (80,78,"t = 6h")]

for px,py,label in points:
    ax[0].scatter(px,py,color="#ff7f0e",zorder=4)
    ax[0].text(px+2,py,label,color="#ff7f0e")


ax[0].annotate("",xy=(55,50),xytext=(50,54),
               arrowprops=dict(arrowstyle="->",color="#ff7f0e",lw=2))

ax[0].annotate("",xy=(100,63),xytext=(80,78),
               arrowprops=dict(arrowstyle="->",color="#ff7f0e",lw=2))

ax[0].set_xlim(18,105)
ax[0].set_ylim(28,82)

ax[0].set_xlabel("x (km)")
ax[0].set_ylabel("y (km)")

ax[0].set_title("Limitation L1: Frozen Motion Field\n∂V/∂t = 0 introduces growing displacement error")
ax[0].legend()

threshold = 0.1
p_zero = 0.55
continuous_weight = 1 - p_zero

r = np.linspace(0,7,500)

sigma = 0.9
mu = np.log(1.2)

pdf = lognorm.pdf(r, s=sigma, scale=np.exp(mu))

pdf[r < threshold] = 0
pdf = continuous_weight * pdf

ax[1].plot(r, pdf, color="#1f77b4", linewidth=2,
           label="Continuous rain part $f_R(r)$")
ax[1].fill_between(r, pdf, color="#1f77b4", alpha=0.25)

ax[1].axvline(threshold, color="gray", linestyle="--",
              linewidth=2, label="Truncation at 0.1 mm/h")

ax[1].bar(0, p_zero, width=0.18, color="#e74c3c",
          alpha=0.8, label=r"$P(R=0)=0.55$ (zero-inflation)")

ax[1].set_xlim(-0.3,7)
ax[1].set_ylim(0,0.6)

ax[1].set_xlabel("Rainfall Intensity $R$ (mm/h)")
ax[1].set_ylabel("Probability Mass / Density")

ax[1].set_title("Limitation L3: Zero-Inflation Anomaly\nTrue $R(x,t)$ is mixed discrete-continuous")
ax[1].legend()

plt.tight_layout()
plt.show()